import assert from 'node:assert/strict';
import { loadApp } from './_harness.mjs';
const DOT = '<span class="think-dot">·</span>';
const { sandbox, clock } = loadApp();
const onEvent = sandbox.window.__agent.onEvent;
const chat = sandbox.document.getElementById('chat');
clock.now = 0;
onEvent({type:'user_message', content:'go'});
onEvent({type:'status', convo_tokens:999999});
clock.now = 680000;
onEvent({type:'thinking_start'});
const row = chat.children.at(-1);
assert.equal(row.tagName, 'details', 'native details provides mouse and keyboard expansion');
assert.equal(row.querySelector('.think-meta').innerHTML, ' 11m 20s');
onEvent({type:'reasoning_stream', stream_id:'s', phase:'delta', content:'Consider', tokens:15000, tokens_per_second:86, estimated:true});
assert.equal(row.querySelector('.think-meta').innerHTML, ` 11m 20s${DOT}15k tokens${DOT}86 tok/sec`);
assert.ok(row.querySelector('.think-meta').title.includes('estimated'));
assert.equal(row.querySelector('.think-content').textContent, 'Consider');
row.open = true;
onEvent({type:'reasoning_stream', stream_id:'s', phase:'delta', content:'Consider <script> safely', tokens:15001});
assert.equal(row.open, true, 'stream updates preserve expansion');
assert.equal(row.querySelector('.think-content').textContent, 'Consider <script> safely');
onEvent({type:'reasoning_stream', stream_id:'s', phase:'end', content:'Complete', tokens:15010, estimated:false});
onEvent({type:'thought', text:'Answer explanation'});
assert.ok(chat.children.includes(row), 'completed reasoning remains inspectable');
assert.equal(row.querySelector('.think-label').textContent, 'Thought');
onEvent({type:'thinking_start'});
const next = chat.children.at(-1);
assert.ok(!next.querySelector('.think-meta').innerHTML.includes('tokens'), 'new request resets usage');
onEvent({type:'reasoning_stream', stream_id:'t', phase:'reset', content:'Interrupted reasoning', tokens:3});
assert.equal(next.querySelector('.think-label').textContent, 'Interrupted');
console.log('thinking expansion, streaming, telemetry and completion: OK');
