# Importing these modules automatically registers their tools with the ToolRegistry.
# Add new tool modules here as the framework grows.
import tools.filesystem
import tools.shell
import tools.apk_tools
import tools.binary_analysis
import tools.native_triage
import tools.hex_patching
import tools.binary_editing
import tools.hash_tools
import tools.code_graph
import tools.text_analysis
import tools.dex_editing
import tools.native_codegen
import tools.android_emulator
import tools.emulator_screen
import tools.vision_tools
import tools.roblox_session
import tools.session_bootstrap
import tools.frida_tools
import tools.plan_tools
import tools.investigation_tools
import tools.ledger_tools
import tools.strategy_tools
import tools.learned_technique
import tools.hook_verification
import tools.skill_tools
import tools.codebase_qa
import tools.reviewer
import tools.web_tools
import tools.meta_tools
import tools.delegation_tools
import tools.workflow_tools
import tools.command_tools
